Revert "Switch desugaring lib to desugar_jdk_libs_nio"
This reverts commit 7efb1f81b5d2cf988a2450b95edc3517b52e51b5.

For some weird reason, mina-sshd works fine without desugaring NIO on
Android 5 but fails with `java.lang.NoClassDefFoundError: Failed resolution
of: Ljava/nio/channels/AsynchronousChannelGroup;` before reverting this